version: 2.0

references:

  workspace_root: &workspace_root
    /tmp/workspace
    
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

jobs:
  setup_project:
    docker:
    - image: circleci/python:3.6.3
    steps:
    - *attach_workspace
    - checkout
    - run:
        name: Install Python dependencies in a venv
        command: |
          python3 -m venv env
          source ./env/bin/activate 
          python -m pip install -r requirements.txt
  chrome-tests:
    docker:
    - image: circleci/python:3.6.3
    - image: selenium/standalone-chrome:3.141.59-iron
    steps:
    - *attach_workspace
    - run:
        name: run tests chrome
        command: |
          . env/bin/activate
          ./run-tests.sh -b chrome -p Tests
  firefox-tests:
    docker:
    - image: circleci/python:3.6.3
    - image: selenium/standalone-firefox:3.141.59-iron
    steps:
    - *attach_workspace
    - run:
        name: run tests firefox
        command: |
          . env/bin/activate
          ./run-tests.sh -b firefox -p Tests
workflows:
  version: 2
  run_e2e_tests:
    jobs:
      - setup_project
      - chrome-tests:
          requires:
            - setup_project
      - firefox-tests:
          requires:
          - setup_project