# Python CircleCI 2.0 configuration file
      
version: 2
  jobs:
    chrome-tests:
      docker:
        - image: circleci/python:3.6.3
        - image: selenium/standalone-chrome:3.141.59-iron
      working_directory: ~/repo

      steps:
        - checkout

        - run:
            name: install dependencies
            command: |
              python3 -m venv venv
              . venv/bin/activate
              pip install -r requirements.txt

        - run:
            name: run tests chrome
            command: |
              . venv/bin/activate
              ./run-tests.sh -b chrome -p Tests

    firefox-tests:
      docker:
        - image: circleci/python:3.6.3
        - image: selenium/standalone-firefox:3.141.59-iron
      
      working_directory: ~/repo

      steps:
        - checkout

        - run:
            name: install dependencies
            command: |
              python3 -m venv venv
              . venv/bin/activate
              pip install -r requirements.txt

        - run:
            name: run tests firefox
            command: |
              . venv/bin/activate
              ./run-tests.sh -b firefox -p Tests
    
workflows:
  version: 2
  build:
    jobs:
      - chrome-tests
      - firefox-tests
      