# Python CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.3
      - image: selenium/standalone-firefox:3.141.59-iron

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - run:
          name: run tests firefox
          command: |
            . venv/bin/activate
            ./run-tests.sh -b firefox -p Tests

  build2: 
    docker:

      - image: circleci/python:3.6.3
      - image: selenium/standalone-chrome:3.141.59-iron

    working_directory: ~/repo
    
    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - run:
          name: run tests chrome
          command: |
            . venv/bin/activate
            ./run-tests.sh -b chrome -p Tests

workflows:
  version: 2

  my_workflow:
    jobs:
      - build
      - build2
      
# workflows:
#   version: 2
#   build_accept_deploy:
#     jobs:
#       - build
#       - acceptance_test_1:
#           requires:
#             - build
#       - acceptance_test_2:
#           requires:
#             - build
#       - acceptance_test_3:
#           requires:
#             - build
#       - acceptance_test_4:
#           requires:
#             - build
#       - deploy:
#           requires:
#             - acceptance_test_1
#             - acceptance_test_2
#             - acceptance_test_3
#             - acceptance_test_4